name: 'Get GitHub App Token'
description: 'Retrieve an authentication token for a GitHub App'
inputs:
  app_id:
    description: 'ID of GitHub App'
    required: true
  private_key:
    description: 'Private key for the GitHub App'
    required: true
outputs:
  token: 
    description: 'Authentication token'
runs:
  using: 'node16'
  main: 'index.js'
